img = double(imread('flutter.png'));
E_roberts = edge(img,'roberts');
E_prewitt = edge(img,'prewitt');
E_sobel = edge(img,'sobel');
E_canny = edge(img, 'canny');
figure,imagesc(img),axis image, colormap gray, colorbar;
figure,imagesc(E_roberts),axis image, colormap gray, colorbar;
figure,imagesc(E_prewitt),axis image, colormap gray, colorbar;
figure,imagesc(E_sobel),axis image, colormap gray, colorbar;
figure,imagesc(E_canny),axis image, colormap gray, colorbar;